#!/bin/bash

temp_dir=$(mktemp -d)
trap 'rm -rf "$temp_dir"' EXIT

curl -sL https://raw.githubusercontent.com/Fazzoc/Fedora-Minimal-Setup/main/setup -o "$temp_dir/setup"
chmod +x "$temp_dir/setup"

sudo bash -c "$temp_dir/setup"